### ISSUE TITLE
Elaborate the use of iteration in a programming language

### ISSUE THREAD

**Issue by Aaditya-Mishra** [Developer-Student-Clubs-MMDU/Computer-Programming#1]
Point to include

> what is iteration?
> Purpose of Iteration.
> Some common iteration statements

**Comment by void-57** [comment]
Please Assign me @Aaditya-Mishra

**Comment by ankit060801** [comment]
hey bro please assign me @Aaditya-Mishra

**Comment by void-57** [comment]
@Aaditya-Mishra  I have  contributed please go through it
