### ISSUE TITLE
Static vs Dynamic memory allocation

### ISSUE THREAD

**Issue by Aaditya-Mishra** [Developer-Student-Clubs-MMDU/Computer-Programming#2]
Point to mention

- write the core concept of static and dynamic memory allocation
- Include examples of c programming language

**Comment by ankit060801** [comment]
Please assign me!

**Comment by yash-sharma13** [comment]
I'll do it

**Comment by Aaditya-Mishra** [comment]
> Please assign me!

Join our discord server for further discussion
https://discord.gg/Gkb4j9rUPD
