### ISSUE TITLE
Difference between Spread operator and Rest parameters in Javascript

### ISSUE THREAD

**Issue by Aaditya-Mishra** [Developer-Student-Clubs-MMDU/Computer-Programming#6]
Points to put in the article:-
- Difference in tabular format
- Include example
- Provide the code for both concepts

**Comment by shikhar13012001** [comment]
I would like to work on this issue

**Comment by Aaditya-Mishra** [comment]
Issue assigned to @shikhar13012001

**Comment by itsjatinnagar** [comment]
Issue assigned to @7sakshi7
