### ISSUE TITLE
Loops in JavaScript

### ISSUE THREAD

**Issue by Aaditya-Mishra** [Developer-Student-Clubs-MMDU/Computer-Programming#8]
Write about the types of loops available in javascript.
Must include syntax and example

**Comment by Sayan2908** [comment]
@Aaditya-Mishra can I work on it?

**Comment by Aaditya-Mishra** [comment]
@Sayan2908 issue is assigned to you

**Comment by Sayan2908** [comment]
@Aaditya-Mishra , @7sakshi7 I had added a pull request yesterday could you please check its viability or I have to make more changes
