### ISSUE TITLE
Concept of Virtual Function in C++

### ISSUE THREAD

**Issue by Aaditya-Mishra** [Developer-Student-Clubs-MMDU/Computer-Programming#9]
Elaborate on the concept of a virtual function and must include these points:

1. Why do we need a virtual function?
2. Include examples related to that.

**Comment by aditya-agr** [comment]
I can to this, assign it to me.

**Comment by Aaditya-Mishra** [comment]
@aditya-agr issue assigned to you.

**Comment by aditya-agr** [comment]
ok I will make a pr.

**Comment by aditya-agr** [comment]
@Aaditya-Mishra  merge the pr.
